server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borrow_db
    username: root
    password: rootaccount

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: mysecretkeymysecretkeymysecretkey
